var potentials = 	

	[
		{
		  "name":"John Snow",
		  "photo":"http://img.huffingtonpost.com/asset/scalefit_630_noupscale/56e024e81500002a000b1742.jpeg?cache=jzkjufoi3w,
		  "scores":[
		     5,
		     3,
		     1,
		     3,
		     1,
		     1,
		     1,
		     2,
		     4,
		     1
		   ]
		},
		{
		  "name":"Captain Planet",
		  "photo":"https://thumbs.mic.com/YWUyM2MyZTAwYiMvQlM3N2ZHM2dESDhuSjV2aGpQZWF1a0ZQeW5RPS8xMTl4MDoxMzgyeDY1My8xMjgweDYyMC9maWx0ZXJzOnF1YWxpdHkoNzUpL2h0dHBzOi8vczMuYW1hem9uYXdzLmNvbS9wb2xpY3ltaWMtaW1hZ2VzL3l2YmNoZG5yZGVja2pzbnh6Z2lhbTlwZGhrNmcyanNpY2tlcGxnd3c4NHNyanNzeW5xMG8wZ2ZpZW82OXZma3ouanBn.jpg",
		  "scores":[
		     3,
		     3,
		     3,
		     4,
		     5,
		     1,
		     2,
		     5,
		     1,
		     5
		   ]
		},
		{
		  "name":"Jinx",
		  "photo":"http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_2.jpg",
		  "scores":[
		     3,
		     2,
		     1,
		     1,
		     5,
		     3,
		     4,
		     2,
		     1,
		     4
		   ]
		},
		{
		  "name":"Sentinal Robot",
		  "photo":"http://vignette1.wikia.nocookie.net/robotsupremacy/images/0/08/Squiddy.jpg/revision/latest?cb=20120512111003",
		  "scores":[
		     1,
		     1,
		     4,
		     1,
		     4,
		     1,
		     2,
		     3,
		     4,
		     1
		   ]
		},
		{
		  "name":"Links",
		  "photo":"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQrbHSYZLrw7cAMVBMematnFC9H_ifr9Xp0_ySe2ALjpemXIHruKQ",
		  "scores":[
		     1,
		     4,
		     4,
		     2,
		     3,
		     4,
		     3,
		     2,
		     3,
		     3
		   ]
		},
		{
		  "name":"Lux",
		  "photo":"http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_5.jpg",
		  "scores":[
		     5,
		     5,
		     5,
		     5,
		     3,
		     3,
		     2,
		     2,
		     1,
		     1
		   ]
		},
		

	]

module.exports = possibleFriends;